### ISSUE TITLE
Inconsistency between manual daily average and Daily fetch

### ISSUE THREAD

**Issue by alceballosa** [meteostat/meteostat-python#87]
Hi!

First of all, thank you for making this amazing library available. It has been incredibly useful for my research!

I'm trying to get some temperature and humidity time series for my work. However, seeing that humidity min/max are not in the Daily class by default I decided to do the manual aggregation as described in #68. However, I get very different time series, at least in Python 3.85 with meteostat 1.6.0 and pandas 1.1.3.

Snippet:

```python
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Hourly, Stations, Daily

start = datetime(2007, 12,30)
end = datetime(2021, 12, 31)
lat, lon = 6.25, -75.5

stations = Stations()
station = stations.nearby(lat, lon).fetch(1)
data_daily = Daily(station, start, end, model = True).fetch()
data_agg = Hourly(station, start, end, timezone = "America/Bogota", model = True)
data_agg = data_agg.normalize().aggregate('1D').fetch()

fig = plt.figure()
plt.plot(data_daily.index.date, data_daily["tavg"].values, label = "Daily mean by Meteostat")
plt.plot(data_agg.index.date, data_agg["temp"].values, color = "black", label = "Daily mean calculated with aggregate", linewidth = 0.25)


plt.legend()
```

Any ideas on why this might be happening? FWIW, the default Daily output from meteostat seems more consistent but I don't really know what might be happening to cause both methods to output such different results.

Thank you so much in advance!

**Comment by clampr** [comment]
Hi @alceballosa,

Glad to hear you like the library! :)

These differences are, to a certain degree, expected behaviour. However, between 2018 & 2020 it seems like quite a difference:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/12759785/158479939-79d40b96-495f-498a-b9fe-e72aa9f2544e.png">

Usually, the reason is that most daily records aren't aggregated from hourly observations by Meteostat itself. The weather services often provide daily data themselves. More information is available in the [FAQ](https://dev.meteostat.net/faq.html#data).

But I think we'll need a better QA/validation at some point. Also, we should pull data directly from the national weather service of each country. But that's a time-intensive task that will require more contributors on the [Meteor repo](https://github.com/meteostat/meteor).

Sorry, but I can only advise you to use the daily data directly if possible atm.

**Comment by alceballosa** [comment]
Hi @clampr ! 

Thank you very much for your reply. That indeed seems to be the case. I ended up using the daily temperature data and the hourly aggregates for relative humidity combined with data from the Colombian weather service to fill gaps.

By the way, let me know if you want me to open another issue for this but, are there any public details on the source of the model data you use to complement the station measurements?

Kind regards,

Alberto

**Comment by alceballosa** [comment]
Thanks for your reply Christian, I'll check those sources and close the issue :)

Kindly, 

Alberto
